name: Build PDF

on:
    # Triggers the workflow on push or pull request events but only for the main branch
    push:
        branches: [main, release**]
    # Allows us to run the workflow manually from the Actions tab
    workflow_dispatch:

jobs:
  build-website:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - run: nix build

      - run: mkdir -p out && cp -r ./result/* out

      - name: Store website
        uses: ./.github/actions/upload-artifact
        with:
          name: website
          path: ./out

  deploy-site:
    needs: build-website
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get nix build output
        uses: ./.github/actions/download-artifact
        with:
          name: website

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload GH pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './out'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
